Update homepage charts
VA-Explorer/va_explorer pull request #237
Opened 2022-05-06 14:14 UTC by deastman

2022-06-06 22:01 UTC, ajbarnes requested changes

2022-06-08 12:24 UTC, deastman commented on va_explorer/templates/base.html
> +    <link href="{% static 'vendor/fontello-a86a8ad9/css/fontello.css' %}" rel="stylesheet">
No minified css or version for fontello. If we wanted to use a minified css file, we'd have to minify it ourselves.

Fontello is a website where a developer can handpick icons from different libraries (fontawesome is one such library) and download the relevant font files and css for showing those icons (see: https://fontello.com/) The letters after fontello in the directory name are a hash that just represent the download instance.

2022-06-08 12:26 UTC, deastman commented on va_explorer/static/vendor/fontello-a86a8ad9/demo.html
> +      src: url('./font/fontello.eot?20711964');
Removed demo and css files we don't need: 
[a6be1ff](https://github.com/VA-Explorer/va_explorer/pull/237/commits/a6be1ff4ba5cdb2307b146dac453335d61414e80)

2022-06-08 12:26 UTC, deastman commented on va_explorer/static/vendor/fontello-a86a8ad9/demo.html
> +  <!--[if lt IE 9]><script language="javascript" type="text/javascript" src="//html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
Removed! [a6be1ff](https://github.com/VA-Explorer/va_explorer/pull/237/commits/a6be1ff4ba5cdb2307b146dac453335d61414e80)

2022-06-08 12:27 UTC, deastman commented on va_explorer/static/vendor/fontello-a86a8ad9/css/fontello-ie7.css
> +[class^="icon-"], [class*=" icon-"] {
Removed! 
[a6be1ff](https://github.com/VA-Explorer/va_explorer/pull/237/commits/a6be1ff4ba5cdb2307b146dac453335d61414e80)

2022-06-08 12:27 UTC, deastman commented on va_explorer/static/vendor/fontello-a86a8ad9/LICENSE.txt
> +   Homepage:  http://fortawesome.github.com/Font-Awesome/
Yes, license is correct as these are Font Awesome icons that are provided individually through fontello. See earlier comment.

2022-06-08 12:28 UTC, deastman commented on va_explorer/static/vendor/fontello-a86a8ad9/css/fontello.css
> +.icon-up-dir:before { content: '\e800'; } /* '' */
Not sure of the intention of those comments. They appear automatically in the downloaded css.

2022-06-08 12:31 UTC, deastman commented on va_explorer/static/js/logging_event_handlers.js
>          console.log('clicked demo tab')
[8b5675c](https://github.com/VA-Explorer/va_explorer/pull/237/commits/8b5675cd3d70b3bd48efeae11a2c79e4162d62df)

2022-06-08 12:32 UTC, deastman commented on va_explorer/va_analytics/dash_apps/va_dashboard.py
> +                            className="icon-info-circled",
Sorry for missing this one and thank you for the catch!
[8024f0c](https://github.com/VA-Explorer/va_explorer/pull/237/commits/8024f0c6110620f3f64735c8a1404bd8dbac89b4)

2022-06-08 17:03 UTC, ajbarnes commented on va_explorer/templates/base.html
> +    <link href="{% static 'vendor/fontello-a86a8ad9/css/fontello.css' %}" rel="stylesheet">
Should we add documentation for devs on how to update fontello if we ever want to add/remove icons in the future?

2022-06-22 19:05 UTC, deastman commented on va_explorer/templates/base.html
> +    <link href="{% static 'vendor/fontello-a86a8ad9/css/fontello.css' %}" rel="stylesheet">
Added at long last! [57d6db9](https://github.com/VA-Explorer/va_explorer/pull/237/commits/57d6db93808204f02eef26159336bb8402e75062)

2022-06-22 20:05 UTC, merged