Remove ownership-based field worker permissions
VA-Explorer/va_explorer pull request #261
Opened 2023-02-14 21:32 UTC by kji-mitre

Resolves #258 
* Reverts field worker permissions to location-based model
* Removes field worker to VA linking capability
* Removes dedicated VA username data elements
* Updates documentation to reflect changes

2023-02-22 01:02 UTC, ajbarnes requested changes
I pulled the branch and confirmed expected functionality via tests and a local run. The app and the docs are looking good, nice work! I left some minor comments during code review that I think we should address before final approval, but otherwise I think this is good to go.

2023-02-22 16:00 UTC, kji-mitre commented on va_explorer/va_data_management/models.py
> -    username = models.TextField("Username", blank=True)
Makes sense! I've restored the property.

2023-02-22 16:01 UTC, kji-mitre commented on docs/training/admin_guides.md
> -
Oops! I've removed mention of the `--match-threshold` option.

2023-02-28 15:58 UTC, ajbarnes approved these changes

2023-02-28 15:58 UTC, merged