Dev user access defaults
VA-Explorer/va_explorer pull request #33
Opened 2021-01-27 20:10 UTC by deastman

2021-02-05 00:42 UTC, pkmitre reviewed
1. There's a merge commit in the commit history, and what looks like a duplicate commit; I tried to untangle it and pushed my attempt to the `dev_user_access_defaults_rebase` branch, if you'd like to take a look and see whether that new branch correctly captures all the intended changes

2. Do the new tests with selenium require Firefox to be installed? We should discuss whether we want that as a development requirement

2021-02-05 03:10 UTC, pkmitre requested changes
Take a look at the `dev_user_access_defaults_rebase` branch to see if that would be appropriate for a new pull request.

2021-02-05 14:17 UTC, deastman commented
@pkmitre I will take a look at the rebased branch!

The tests do require Firefox to be installed. Happy to discuss this with the team at a standup!

2021-02-16 22:03 UTC, pkmitre approved these changes

2021-02-16 22:05 UTC, merged