Dev update templates
VA-Explorer/va_explorer pull request #35
Opened 2021-01-29 20:37 UTC by deastman

- Update templates for consistency of styling across the application. 
- Break out pagination into partial for easy sharing across templates (e.g., once Tim's conversion of Verbal Autopsy views to class-based views is merged into master, the partial can just be included within index.html)

2021-02-05 00:41 UTC, pkmitre reviewed
1. There's a merge commit in the commit history, and what looks like a duplicate commit; I tried to untangle it and pushed my attempt to the `dev_user_access_defaults_rebase` branch, if you'd like to take a look and see whether that new branch correctly captures all the intended changes

2. Do the new tests with selenium require Firefox to be installed? We should discuss whether we want that as a development requirement

2021-02-05 03:13 UTC, pkmitre requested changes
Looks like this pull request needs updates now that master has transitioned to class based views; I see a "TODO" about pagination, plus it looks like there are differences in how the templates refer to data for display.

2021-02-05 14:15 UTC, deastman commented
@pkmitre I can resolve the merge conflicts now that Tim's PR has been merged in. I will also bring in the pagination partial.

2021-02-16 21:44 UTC, pkmitre approved these changes

2021-02-16 21:45 UTC, merged